### ISSUE TITLE
[FR] Job-Populator

### ISSUE THREAD

**Issue by Flusinerd** [opensky-to/api#26]
We need to implement a job-populator worker that generates jobs.
**All distances are in nautical miles**

These jobs can either be created "on demand" or whenever a import / job has finished.

Major issues that need to be solved when implementing this feature is:

- [x] Efficient way to get possible airports to generate jobs to the current airport
- [x] Caching for distances between airports (yes or no)
- [x] "Distance Categories" for different job types

Initial idea for categories were:
```
<50,  50-249 , 250-499, 500-999 , 1000-3000, > 3000
```

![image](https://user-images.githubusercontent.com/22977969/124335934-5b6a3400-db9c-11eb-86ad-6d377bc385b0.png)

**Comment by markuskorbel** [comment]
Efficient way to get possible airports to generate jobs to the current airport -> S2Geometry 
Caching for distances between airports (yes or no) -> no
"Distance Categories" for different job types -> EmbrearGuy created those
